/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'Readme',
    {
      type: 'category',
      label: 'Documentation',
      items: ['Documentation/analytics','Documentation/dartdoc','Documentation/libraries'],
    },
    {
      type: 'category',
      label: 'Community',
      items: [ 'Community/Code-of-Conduct','Community/Contributing','Community/faqs','Community/privacypolicy'],
    },
    {
      type: 'category',
      label: 'Accesibility',
      items: ['Accesibility/accesibility-suite','Accesibility/pressAndPress','Accesibility/scrollAndPress','Accesibility/sipAndPuff','Accesibility/wormAccessible'],
    },
    {
      type: 'category',
      label: 'Testing',
      items: ['Testing/Java/Android/Android_Java_Testing',],
    },
  ],
   
};

module.exports = sidebars;
